version: "1"
name: "users"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - 8001:80
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '54320:5432'
