version: "3"
name: "users"
services:
  db:
    container_name: users-database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '54320:5432'

  backend:
    container_name: users-backend
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - 8001:80
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  
  
