"""added user phone number

Revision ID: 980632de102b
Revises: 9907b7318bee
Create Date: 2023-01-21 10:52:32.942134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980632de102b'
down_revision = '9907b7318bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
