"""added region to user

Revision ID: ddeecb351a7c
Revises: 980632de102b
Create Date: 2023-01-21 17:46:28.202777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddeecb351a7c'
down_revision = '980632de102b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    # ### end Alembic commands ###
